[project]
name = "dissertation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "aiohttp>=3.13.2",
  "asyncpg>=0.31.0",
  "debugpy>=1.8.17",
  "fastapi>=0.121.1",
  "jupyter>=1.1.1",
  "matplotlib>=3.10.7",
  "mcp>=1.17.0",
  "mpl-tools>=0.4.1",
  "numpy>=2.3.5",
  "openai>=2.3.0",
  "pandas>=2.3.3",
  "postgres-mcp>=0.2.1",
  "postgres-mcp-server>=1.0.1",
  "psycopg2-binary>=2.9.11",
  "pydantic>=2.12.1",
  "pydantic-settings>=2.11.0",
  "pyodata>=1.11.2",
  "python-dotenv>=1.1.1",
  "scipy>=1.16.3",
]
